name: Flutter Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'

    - name: Install dependencies
      run: |
           cd ./timotime/ 
           flutter pub get

    - name: Build Linux
      run: |
           cd ./timotime/
           flutter build linux --release
