name: Flutter Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        
    - name: Install dependencies from Apt
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y;

        # These packages are listed in the setup instructions for Linux desktop. They may not all be necessary.
        # For reference: https://docs.flutter.dev/get-started/install/linux/desktop
        sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
        
    - name: Install dependencies
      run: |
           cd ./timotime/ 
           flutter pub get

    - name: Build Linux
      run: |
           cd ./timotime/
           flutter build linux --release
