name: Flutter Release Builds

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # ex: v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: |
            cd ./timotime/
            flutter pub get
      - run: |
             cd ./timotime/
             flutter build windows -v
      # - name: Upload Windows Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-build
      #     path: ./timotime/build/windows/runner/Release/

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.29.2'
  #     - run: sudo apt-get update
  #     - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev -y
  #     - run: |
  #           cd ./timotime/
  #           flutter pub get
  #     - run: |
  #            cd ./timotime/
  #            flutter build linux
  #     - name: Upload Linux Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: linux-build
  #         path: ./timotime/build/linux/x64/release/bundle

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.29.2'
  #     - run: |
  #           cd ./timotime/
  #           flutter pub get
  #     - run: |
  #            cd ./timotime/
  #            flutter build macos
  #     - name: Upload macOS Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-build
  #         path: ./timotime/build/macos/Build/Products/Release/

  # attach-assets:
  #   needs: [build-windows, build-linux, build-macos]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: artifacts

  #     - name: Zip builds
  #       run: |
  #         cd artifacts
  #         zip -r windows-${{ github.ref_name }}.zip windows-build
  #         zip -r linux-${{ github.ref_name }}.zip linux-build
  #         zip -r macos-${{ github.ref_name }}.zip macos-build

  #     - name: Upload to release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         files: |
  #           artifacts/windows.zip
  #           artifacts/linux.zip
  #           artifacts/macos.zip
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
